package com.hand.exam.bills.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;


@MultiLanguage
@ExtensionAttribute(disable=true)
@Table(name = "xxfnd_organization_access_b")
public class Organization extends BaseDTO {

     public static final String FIELD_ORGANIZATION_ID = "organizationId";
     public static final String FIELD_ORGANIZATION_NUMBER = "organizationNumber";
     public static final String FIELD_ORGANIZATION_NAME = "organizationName";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long organizationId; //表ID，主键，供其他表做外键

     @NotEmpty
     @Length(max = 60)
     private String organizationNumber; //组织编码

     @NotEmpty
     @Length(max = 60)
     private String organizationName; //组织名称

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setOrganizationId(Long organizationId){
         this.organizationId = organizationId;
     }

     public Long getOrganizationId(){
         return organizationId;
     }

     public void setOrganizationNumber(String organizationNumber){
         this.organizationNumber = organizationNumber;
     }

     public String getOrganizationNumber(){
         return organizationNumber;
     }

     public void setOrganizationName(String organizationName){
         this.organizationName = organizationName;
     }

     public String getOrganizationName(){
         return organizationName;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
