package com.hand.exam.bills.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "xxinv_shiped_doc")
public class ShipedDoc extends BaseDTO {

     public static final String FIELD_SHIP_DOC_ID = "shipDocId";
     public static final String FIELD_ORGANIZATION_ID = "organizationId";
     public static final String FIELD_DOC_NUMBER = "docNumber";
     public static final String FIELD_TO_ORGANIZATION_ID = "toOrganizationId";
     public static final String FIELD_SHIPPED_TIME = "shippedTime";
     public static final String FIELD_DOC_TYPE = "docType";
     public static final String FIELD_SHIPPMENT_STATUS = "shippmentStatus";
     public static final String FIELD_CONFIRMER_ID = "confirmerId";
     public static final String FIELD_DRIVER_NAME = "driverName";
     public static final String FIELD_DRIVER_PHONE = "driverPhone";
     public static final String FIELD_PLATE_NUMBER = "plateNumber";
     public static final String FIELD_FREIGHT = "freight";
     public static final String FIELD_MEMO = "memo";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long shipDocId; //表ID

     @NotNull
     private Long organizationId; //组织ID

     @NotEmpty
     @Length(max = 240)
     private String docNumber; //发货单号

     private Long toOrganizationId; //目标仓库

     private Date shippedTime; //发货时间

     @NotEmpty
     @Length(max = 50)
     private String docType; //ISSUED(出库单)/RETURN(入库单)

     @NotEmpty
     @Length(max = 30)
     private String shippmentStatus; //PENDING(未发货)/(CONFIRMED)已确认/SHIPPED(已发货)

     private Long confirmerId; //确认人用户ID

     @Length(max = 30)
     private String driverName; //司机姓名

     @Length(max = 30)
     private String driverPhone; //司机电话

     @Length(max = 30)
     private String plateNumber; //车牌号

     private Double freight; //运费

     @Length(max = 65535)
     private String memo; //备注

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setShipDocId(Long shipDocId){
         this.shipDocId = shipDocId;
     }

     public Long getShipDocId(){
         return shipDocId;
     }

     public void setOrganizationId(Long organizationId){
         this.organizationId = organizationId;
     }

     public Long getOrganizationId(){
         return organizationId;
     }

     public void setDocNumber(String docNumber){
         this.docNumber = docNumber;
     }

     public String getDocNumber(){
         return docNumber;
     }

     public void setToOrganizationId(Long toOrganizationId){
         this.toOrganizationId = toOrganizationId;
     }

     public Long getToOrganizationId(){
         return toOrganizationId;
     }

     public void setShippedTime(Date shippedTime){
         this.shippedTime = shippedTime;
     }

     public Date getShippedTime(){
         return shippedTime;
     }

     public void setDocType(String docType){
         this.docType = docType;
     }

     public String getDocType(){
         return docType;
     }

     public void setShippmentStatus(String shippmentStatus){
         this.shippmentStatus = shippmentStatus;
     }

     public String getShippmentStatus(){
         return shippmentStatus;
     }

     public void setConfirmerId(Long confirmerId){
         this.confirmerId = confirmerId;
     }

     public Long getConfirmerId(){
         return confirmerId;
     }

     public void setDriverName(String driverName){
         this.driverName = driverName;
     }

     public String getDriverName(){
         return driverName;
     }

     public void setDriverPhone(String driverPhone){
         this.driverPhone = driverPhone;
     }

     public String getDriverPhone(){
         return driverPhone;
     }

     public void setPlateNumber(String plateNumber){
         this.plateNumber = plateNumber;
     }

     public String getPlateNumber(){
         return plateNumber;
     }

     public void setFreight(Double freight){
         this.freight = freight;
     }

     public Double getFreight(){
         return freight;
     }

     public void setMemo(String memo){
         this.memo = memo;
     }

     public String getMemo(){
         return memo;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
