package com.hand.exam.bills.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "xxinv_material_txns")
public class Txns extends BaseDTO {

     public static final String FIELD_TRANSACTION_ID = "transactionId";
     public static final String FIELD_ORGANIZATION_ID = "organizationId";
     public static final String FIELD_SUBINVENTORY_CODE = "subinventoryCode";
     public static final String FIELD_TO_ORGANIZATION_ID = "toOrganizationId";
     public static final String FIELD_TO_SUBINVENTORY_CODE = "toSubinventoryCode";
     public static final String FIELD_INVENTORY_ITEM_ID = "inventoryItemId";
     public static final String FIELD_LOT_NUMBER = "lotNumber";
     public static final String FIELD_TRANSACTION_TYPE_NAME = "transactionTypeName";
     public static final String FIELD_TRANSACTION_QUANTITY = "transactionQuantity";
     public static final String FIELD_UOM_CODE = "uomCode";
     public static final String FIELD_TRANSACTION_DATE = "transactionDate";
     public static final String FIELD_SOURCE_TABLE = "sourceTable";
     public static final String FIELD_SOURCE_KEY1 = "sourceKey1";
     public static final String FIELD_SOURCE_KEY2 = "sourceKey2";
     public static final String FIELD_SOURCE_DOC = "sourceDoc";
     public static final String FIELD_FUNCTION_CODE = "functionCode";
     public static final String FIELD_PROCESS_STATUS = "processStatus";
     public static final String FIELD_PROCESS_MESSAGE = "processMessage";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long transactionId; //表ID，主键，供其他表做外键

     private Long organizationId;

     @Length(max = 50)
     private String subinventoryCode; //来源子库存编码

     private Long toOrganizationId;

     @Length(max = 50)
     private String toSubinventoryCode;

     @NotNull
     private Long inventoryItemId; //物料

     @Length(max = 50)
     private String lotNumber; //批次

     @NotEmpty
     @Length(max = 100)
     private String transactionTypeName; //事务处理类型名称（Account Alias Issue：账户别名出库；Account Issue ： 账户出库；Subinventory Transfer：字库转移； Direct Organization Transfer：组织间转移；Purchase Receipt：采购接收）

     private Double transactionQuantity; //事务处理数量

     @NotEmpty
     @Length(max = 30)
     private String uomCode; //单位代码

     private Date transactionDate; //事务处理时间

     @Length(max = 30)
     private String sourceTable; //事务来源表名

     @Length(max = 30)
     private String sourceKey1; //来源主键1

     @Length(max = 30)
     private String sourceKey2; //来源主键2

     @Length(max = 100)
     private String sourceDoc; //单据编号

     @Length(max = 100)
     private String functionCode; //HAP功能编码

     @Length(max = 30)
     private String processStatus; //同步状态:N/E/S(预留回写)

     @Length(max = 65535)
     private String processMessage; //ERP接口消息(预留回写)

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setTransactionId(Long transactionId){
         this.transactionId = transactionId;
     }

     public Long getTransactionId(){
         return transactionId;
     }

     public void setOrganizationId(Long organizationId){
         this.organizationId = organizationId;
     }

     public Long getOrganizationId(){
         return organizationId;
     }

     public void setSubinventoryCode(String subinventoryCode){
         this.subinventoryCode = subinventoryCode;
     }

     public String getSubinventoryCode(){
         return subinventoryCode;
     }

     public void setToOrganizationId(Long toOrganizationId){
         this.toOrganizationId = toOrganizationId;
     }

     public Long getToOrganizationId(){
         return toOrganizationId;
     }

     public void setToSubinventoryCode(String toSubinventoryCode){
         this.toSubinventoryCode = toSubinventoryCode;
     }

     public String getToSubinventoryCode(){
         return toSubinventoryCode;
     }

     public void setInventoryItemId(Long inventoryItemId){
         this.inventoryItemId = inventoryItemId;
     }

     public Long getInventoryItemId(){
         return inventoryItemId;
     }

     public void setLotNumber(String lotNumber){
         this.lotNumber = lotNumber;
     }

     public String getLotNumber(){
         return lotNumber;
     }

     public void setTransactionTypeName(String transactionTypeName){
         this.transactionTypeName = transactionTypeName;
     }

     public String getTransactionTypeName(){
         return transactionTypeName;
     }

     public void setTransactionQuantity(Double transactionQuantity){
         this.transactionQuantity = transactionQuantity;
     }

     public Double getTransactionQuantity(){
         return transactionQuantity;
     }

     public void setUomCode(String uomCode){
         this.uomCode = uomCode;
     }

     public String getUomCode(){
         return uomCode;
     }

     public void setTransactionDate(Date transactionDate){
         this.transactionDate = transactionDate;
     }

     public Date getTransactionDate(){
         return transactionDate;
     }

     public void setSourceTable(String sourceTable){
         this.sourceTable = sourceTable;
     }

     public String getSourceTable(){
         return sourceTable;
     }

     public void setSourceKey1(String sourceKey1){
         this.sourceKey1 = sourceKey1;
     }

     public String getSourceKey1(){
         return sourceKey1;
     }

     public void setSourceKey2(String sourceKey2){
         this.sourceKey2 = sourceKey2;
     }

     public String getSourceKey2(){
         return sourceKey2;
     }

     public void setSourceDoc(String sourceDoc){
         this.sourceDoc = sourceDoc;
     }

     public String getSourceDoc(){
         return sourceDoc;
     }

     public void setFunctionCode(String functionCode){
         this.functionCode = functionCode;
     }

     public String getFunctionCode(){
         return functionCode;
     }

     public void setProcessStatus(String processStatus){
         this.processStatus = processStatus;
     }

     public String getProcessStatus(){
         return processStatus;
     }

     public void setProcessMessage(String processMessage){
         this.processMessage = processMessage;
     }

     public String getProcessMessage(){
         return processMessage;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
